language: node_js
node_js:
  - "6"
install:
  - yarn install
  - npm install -g codecov
script:
  - npm run cover 
after_success:
  - npm run semantic-release
  - bash <(curl -s https://codecov.io/bash)
