language: node_js
node_js:
  - "4.5"
  - "5"
  - "6"
  - "7"
install:
  - npm install
  - npm install -g codecov
script:
  - npm run cover 
after_success:
  - npm run semantic-release
  - bash <(curl -s https://codecov.io/bash)
